version: "3"

services:
  web:
    image: ttu-web
    container_name: web
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - 8000:8000
  db:
    image: postgres:alpine
    container_name: db
    restart: unless-stopped
    # ports:
    #   - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ttupassword1
      POSTGRES_USER: ttu
      POSTGRES_DB: ttu

volumes:
  pgdata:
    driver: local