services:
  tt-app:
    image: transit_tracker:0.4
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - '8000:8000'
    volumes:
      - ./data:/code/data
volumes:
  data: